name: Exploring variable and secrets

on: push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker build
          run: docker build -t docker.io/dockerUsername/imageName:latest
        
        - name: Docker login
          run: docker login --userrname=dockerUsername --password=s3cUrePaSsw0rd

        - name: Docker Publish
          run: docker push docker.io/dockerUsernamne/imageName:latest
        
    deploy:
        needs: docker
        runs-on: ubuntu-latest

        steps:
        - name: Docker Run
          run: docker run -d -p8080:80 docker.io/dockerUsername/imageName:latest

