name: multipleJobs

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Building the app
          run: echo "Builing stage..."
    
    Test_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:
        - name: Test the app
          run: echo "testing....."
    
    Deploy_job:
        runs-on: ubuntu-latest
        needs: [build_job, Test_job]
        steps:
        - name: Deploy the app
          run: echo "Deploying the applicaion on server .. "
    
    

