name: multipleJobs

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Building the app
          run: |
            echo "Builing stage..."
            echo"hello I am here" >>  output.txt
        
        - name: upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: ./output.txt
          
    
    Test_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:
        - name: Test the app
          run: echo "testing....."
        - name: downlaod Test file
          uses: actions/download-artifact@v3
          with:
            name: my-artifact
        - name: checking file is present
          run: ls 
    
    Deploy_job:
        runs-on: ubuntu-latest
        needs: [build_job, Test_job]
        steps:
        - name: Deploy the app
          run: echo "Deploying the applicaion on server .. "
        - name: downlaod Test file
          uses: actions/download-artifact@v3
          with:
            name: my-artifact
        - name: checking file is present
          run: ls 

    
    

